---
apiVersion: v1
kind: ConfigMap
metadata:
  name: confnginx
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
        worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      #include       /etc/nginx/html/;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name node-api-test;
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location /healthz {
          return 200;
        }

        location / {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://10.40.0.5:3333;
          #proxy_set_header X-Forwarded-For $remote_addr;
          #proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $http_host;
          #proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_http_version 1.1;
        }
       }

      server {
        listen 80;
        server_name hello-blue-whale;
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location /healthz {
          return 200;
        }

        location / {
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_pass http://10.32.0.8:80; #kubectl get endpoints
          #proxy_set_header X-Forwarded-For $remote_addr;
          #proxy_set_header X-Real-IP $remote_addr;
          #proxy_set_header Host $http_host;
          #proxy_set_header Connection "";
          proxy_set_header Host $host;
          proxy_http_version 1.1;
        }
       }
      }

